export const PALETTE_COLORS = [
  {
    hex: "#1e1e1e",
    label: "Black",
    dominantIn: ["Cotton Combed 30s", "Tech-Jersey Sport"],
  },
  { hex: "#f5f5dc", label: "Cream", dominantIn: ["Vintage Washed Linen"] },
  {
    hex: "#4a5d4e",
    label: "Forest Green",
    dominantIn: ["Mulberry Silk Satin"],
  },
  { hex: "#7a4b3a", label: "Brown", dominantIn: [] },
  { hex: "#E61E25", label: "Red", dominantIn: [] },
  { hex: "#e3e3e3", label: "Light Gray", dominantIn: ["Eco-Jersey Organic"] },
  { hex: "#772600", label: "Dark Red", dominantIn: [] },
  { hex: "#b22222", label: "Crimson", dominantIn: [] },
  { hex: "#ffffff", label: "White", dominantIn: ["Eco-Jersey Organic"] },
  { hex: "#9e9e9e", label: "Gray", dominantIn: ["Raw Selvedge Denim"] },
];

export const FABRICS = [
  {
    id: 1,
    name: "Cotton Combed 30s",
    price: "$12.50",
    weight: "180 GSM",
    width: '72"',
    refId: "MA-CT-30S",
    badge: "Core Stock",
    badgeStyle: "light",
    category: "Cotton",
    season: "SS 2024",
    origin: "Bandung, Indonesia",
    composition: "100% Cotton",
    finish: "Combed",
    stock: 120,
    dominantColors: ["#1e1e1e"],
    description:
      "A premium combed cotton with ultra-smooth hand feel and minimal pilling. Ideal for high-end t-shirts, inner garments, and sportswear with a clean drape.",
    archivistNote:
      "The 30s count offers the sweet spot between durability and softness. This batch features a tighter weave than our standard stock, resulting in a more refined surface texture.",
    features: [
      "Excellent moisture absorption for all-day comfort",
      "Pre-shrunk treatment ensures consistent sizing",
      "Suitable for reactive and discharge printing",
    ],
    careInstructions:
      "Machine wash at 40°C. Tumble dry low. Iron on medium heat. Do not bleach.",
    certifications: ["OEKO-TEX® Standard 100", "GOTS Certified"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
  },
  {
    id: 2,
    name: "Vintage Washed Linen",
    price: "$24.00",
    weight: "210 GSM",
    width: '58"',
    refId: "MA-LN-VW",
    badge: "Premium Archive",
    badgeStyle: "primary",
    category: "Linen",
    season: "SS 2024",
    origin: "Lille, France",
    composition: "100% Linen",
    finish: "Stone Washed",
    stock: 42,
    dominantColors: ["#f5f5dc"],
    description:
      "A heavyweight, pre-washed European linen with a characteristic rustic texture and exceptional durability. Ideal for upholstery and structured garments.",
    archivistNote:
      'The "Vintage Washed" designation refers to our proprietary enzyme-washing process that accelerates the natural softening of linen fibers while preserving structural integrity.',
    features: [
      "High abrasion resistance for heavy furniture use",
      "Naturally hypoallergenic and breathable",
      "Develops a soft patina with each subsequent wash",
    ],
    careInstructions:
      "Machine wash at 30°C. Do not tumble dry. Iron while slightly damp for the best structural finish. Avoid direct bleaching agents.",
    certifications: ["OEKO-TEX® Standard 100", "GOTS Certified"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB7iLQpGSnGphDw82Le3ZodtNIhtDuvTbAOLGj8R_qRrQxDknm6uXX_MbSzmNNN9jsqkOuHY3wRO4ipACZwsqalXeT9SG6SsP26e0rgnARoPsOO_8XHdOE6hIesq1m94ICYCAbs49rmb0mYQyUat2cMblD3lw9OFWc-IAwJLH7vqSmMthL3m1ApOa73KOj6k7nqOBruMoazANjRVIYzzs642FphQlSwMTy8m0kbY-aAxm0T4I7SzVYEjq_osUOc6r0wIoze8b5jHmDl",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuB7iLQpGSnGphDw82Le3ZodtNIhtDuvTbAOLGj8R_qRrQxDknm6uXX_MbSzmNNN9jsqkOuHY3wRO4ipACZwsqalXeT9SG6SsP26e0rgnARoPsOO_8XHdOE6hIesq1m94ICYCAbs49rmb0mYQyUat2cMblD3lw9OFWc-IAwJLH7vqSmMthL3m1ApOa73KOj6k7nqOBruMoazANjRVIYzzs642FphQlSwMTy8m0kbY-aAxm0T4I7SzVYEjq_osUOc6r0wIoze8b5jHmDl",
  },
  {
    id: 3,
    name: "Tech-Jersey Sport",
    price: "$18.25",
    weight: "240 GSM",
    width: '60"',
    refId: "MA-KN-TJ",
    badge: "High-Stretch",
    badgeStyle: "light",
    category: "Knit",
    season: "FW 2024",
    origin: "Surabaya, Indonesia",
    composition: "88% Polyester, 12% Spandex",
    finish: "Moisture-Wicking",
    stock: 85,
    dominantColors: ["#1e1e1e"],
    description:
      "High-performance technical jersey engineered for activewear and sports apparel. Features 4-way stretch and superior moisture management for peak athletic performance.",
    archivistNote:
      "This fabric underwent 200+ wash cycle testing at our Surabaya facility. The color retention rate exceeded 98% even after heavy chlorine exposure — a rare achievement for dark technical textiles.",
    features: [
      "4-way stretch with 40% elongation recovery",
      "UV protection factor UPF 50+",
      "Anti-odor treatment lasts 50+ wash cycles",
    ],
    careInstructions:
      "Machine wash cold. Do not bleach. Do not iron. Tumble dry low.",
    certifications: ["OEKO-TEX® Standard 100"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
  },
  {
    id: 4,
    name: "Mulberry Silk Satin",
    price: "$45.00",
    weight: "85 GSM",
    width: '44"',
    refId: "MA-SK-MB",
    badge: null,
    badgeStyle: null,
    category: "Specialty",
    season: "SS 2024",
    origin: "Hangzhou, China",
    composition: "100% Mulberry Silk",
    finish: "Charmeuse Satin",
    stock: 18,
    dominantColors: ["#4a5d4e"],
    description:
      "Grade 6A mulberry silk with a luminous charmeuse finish. The pinnacle of luxury textiles — reserved for couture garments, premium lingerie, and fine home furnishings.",
    archivistNote:
      "Sourced exclusively from silkworms fed on fresh mulberry leaves in Zhejiang Province. Each roll is inspected by hand under diffused natural light to ensure zero surface irregularities.",
    features: [
      "Grade 6A — highest commercial silk grading",
      "Natural temperature regulation for year-round comfort",
      "Hypoallergenic and resistant to dust mites",
    ],
    careInstructions:
      "Dry clean only or hand wash in cold water with silk-specific detergent. Do not wring. Air dry flat away from direct sunlight.",
    certifications: ["OEKO-TEX® Standard 100"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB7iLQpGSnGphDw82Le3ZodtNIhtDuvTbAOLGj8R_qRrQxDknm6uXX_MbSzmNNN9jsqkOuHY3wRO4ipACZwsqalXeT9SG6SsP26e0rgnARoPsOO_8XHdOE6hIesq1m94ICYCAbs49rmb0mYQyUat2cMblD3lw9OFWc-IAwJLH7vqSmMthL3m1ApOa73KOj6k7nqOBruMoazANjRVIYzzs642FphQlSwMTy8m0kbY-aAxm0T4I7SzVYEjq_osUOc6r0wIoze8b5jHmDl",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
  },
  {
    id: 5,
    name: "Raw Selvedge Denim",
    price: "$21.80",
    weight: "14.5 OZ",
    width: '32"',
    refId: "MA-DN-RS",
    badge: "Low Stock",
    badgeStyle: "low-stock",
    category: "Cotton",
    season: "FW 2024",
    origin: "Kojima, Japan",
    composition: "100% Cotton",
    finish: "Raw / Unwashed",
    stock: 9,
    dominantColors: ["#9e9e9e"],
    description:
      "Shuttle-loomed selvedge denim from the historic denim mills of Kojima, Japan. Features the characteristic tight weave and natural indigo fade potential beloved by denim enthusiasts worldwide.",
    archivistNote:
      'This lot was woven on vintage shuttle looms from the 1960s, producing the narrow 32" width and characteristic irregularities that define authentic selvedge. Each roll has a unique warp tension signature.',
    features: [
      "Authentic selvedge edge prevents fraying",
      "Natural indigo dye develops unique fade patterns",
      "Heavyweight construction for premium jeans and workwear",
    ],
    careInstructions:
      "Cold water soak only for first 6 months to set the indigo. Hand wash cold after breaking in. Air dry only. Never machine wash.",
    certifications: ["OEKO-TEX® Standard 100"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAjyDIENCr9zx9MQfqEXt8swrphMLiVwtouSWX2AaamZxvOekJUOuL7vxubt_MiZ6ys3-ZreUxMvKbdjqiGyr3lCJXa9LuDvlo1LfCbzxG4KJbGeb_-5wwMXTuOkr83m8RMmcL_6KinMzYvozX1VYLb8SsK5ZO_xxQrPvrQqeuopLncBVNnZoJLRuaOy6y96yPxD4i9MWDdG84rxzUXJJ1PA2GzTnOz99YtKwLWSG7zwG7Rce-4NQaVaCPw8EbeW5j4P1BymuXpepKN",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAjyDIENCr9zx9MQfqEXt8swrphMLiVwtouSWX2AaamZxvOekJUOuL7vxubt_MiZ6ys3-ZreUxMvKbdjqiGyr3lCJXa9LuDvlo1LfCbzxG4KJbGeb_-5wwMXTuOkr83m8RMmcL_6KinMzYvozX1VYLb8SsK5ZO_xxQrPvrQqeuopLncBVNnZoJLRuaOy6y96yPxD4i9MWDdG84rxzUXJJ1PA2GzTnOz99YtKwLWSG7zwG7Rce-4NQaVaCPw8EbeW5j4P1BymuXpepKN",
  },
  {
    id: 6,
    name: "Eco-Jersey Organic",
    price: "$15.40",
    weight: "160 GSM",
    width: '68"',
    refId: "MA-EC-OR",
    badge: null,
    badgeStyle: null,
    category: "Knit",
    season: "SS 2024",
    origin: "Bandung, Indonesia",
    composition: "100% Organic Cotton",
    finish: "Enzyme Washed",
    stock: 200,
    dominantColors: ["#e3e3e3", "#ffffff"],
    description:
      'Certified organic cotton jersey with a wide 68" width, perfect for zero-waste cutting. Soft, breathable, and environmentally responsible — the everyday fabric of the future.',
    archivistNote:
      "This fabric is produced using 94% less water than conventional cotton. The enzyme-washing finish eliminates the need for chemical softeners while achieving a consistently smooth hand feel.",
    features: [
      "GOTS certified — full supply chain traceability",
      'Wide 68" width maximizes fabric utilization',
      "Natural softness without chemical finishing agents",
    ],
    careInstructions:
      "Machine wash at 40°C. Tumble dry low. Warm iron acceptable. Do not bleach.",
    certifications: ["OEKO-TEX® Standard 100", "GOTS Certified"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB7iLQpGSnGphDw82Le3ZodtNIhtDuvTbAOLGj8R_qRrQxDknm6uXX_MbSzmNNN9jsqkOuHY3wRO4ipACZwsqalXeT9SG6SsP26e0rgnARoPsOO_8XHdOE6hIesq1m94ICYCAbs49rmb0mYQyUat2cMblD3lw9OFWc-IAwJLH7vqSmMthL3m1ApOa73KOj6k7nqOBruMoazANjRVIYzzs642FphQlSwMTy8m0kbY-aAxm0T4I7SzVYEjq_osUOc6r0wIoze8b5jHmDl",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
  },
  {
    id: 7,
    name: "Hemp Canvas Natural",
    price: "$19.90",
    weight: "320 GSM",
    width: '55"',
    refId: "MA-HM-CN",
    badge: "New Arrival",
    badgeStyle: "primary",
    category: "Specialty",
    season: "FW 2024",
    origin: "Yunnan, China",
    composition: "55% Hemp, 45% Organic Cotton",
    finish: "Natural / Unbleached",
    stock: 60,
    dominantColors: ["#f5f5dc"],
    description:
      "An unbleached hemp-cotton blend canvas with natural earthy tones. Exceptionally durable and naturally antimicrobial — ideal for bags, outerwear, and heavy-duty utility garments.",
    archivistNote:
      "Hemp cultivation requires no pesticides and enriches soil health. This specific blend achieves the workability of canvas while maintaining 40% less environmental impact than pure cotton alternatives.",
    features: [
      "Naturally antimicrobial and UV resistant",
      "Softens dramatically with use and washing",
      "Carbon-negative fiber sourcing",
    ],
    careInstructions:
      "Machine wash warm. Tumble dry medium. Iron on high heat while damp. Can be boiled for deep cleaning.",
    certifications: ["OEKO-TEX® Standard 100", "GOTS Certified"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB7iLQpGSnGphDw82Le3ZodtNIhtDuvTbAOLGj8R_qRrQxDknm6uXX_MbSzmNNN9jsqkOuHY3wRO4ipACZwsqalXeT9SG6SsP26e0rgnARoPsOO_8XHdOE6hIesq1m94ICYCAbs49rmb0mYQyUat2cMblD3lw9OFWc-IAwJLH7vqSmMthL3m1ApOa73KOj6k7nqOBruMoazANjRVIYzzs642FphQlSwMTy8m0kbY-aAxm0T4I7SzVYEjq_osUOc6r0wIoze8b5jHmDl",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuB7iLQpGSnGphDw82Le3ZodtNIhtDuvTbAOLGj8R_qRrQxDknm6uXX_MbSzmNNN9jsqkOuHY3wRO4ipACZwsqalXeT9SG6SsP26e0rgnARoPsOO_8XHdOE6hIesq1m94ICYCAbs49rmb0mYQyUat2cMblD3lw9OFWc-IAwJLH7vqSmMthL3m1ApOa73KOj6k7nqOBruMoazANjRVIYzzs642FphQlSwMTy8m0kbY-aAxm0T4I7SzVYEjq_osUOc6r0wIoze8b5jHmDl",
  },
  {
    id: 8,
    name: "French Terry Loopback",
    price: "$22.50",
    weight: "280 GSM",
    width: '62"',
    refId: "MA-FT-LB",
    badge: "Core Stock",
    badgeStyle: "light",
    category: "Cotton",
    season: "FW 2024",
    origin: "Bandung, Indonesia",
    composition: "80% Cotton, 20% Polyester",
    finish: "Brushed Loop",
    stock: 95,
    dominantColors: ["#e3e3e3"],
    description:
      "Classic French terry with exposed loopback on the reverse side. The industry standard for premium sweatshirts, hoodies, and athleisure wear demanding both comfort and structure.",
    archivistNote:
      "Our Loopback variant features a deliberately irregular loop density that creates a subtle texture variation — a characteristic our customers have described as 'hand-crafted authenticity' that differentiates it from mass-market terry.",
    features: [
      "Dense loop construction for superior warmth retention",
      "Smooth jersey face for clean printing surface",
      "Pre-washed for minimal further shrinkage",
    ],
    careInstructions:
      "Machine wash at 40°C inside out. Tumble dry medium. Do not iron on the loopback side.",
    certifications: ["OEKO-TEX® Standard 100"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
  },
  {
    id: 9,
    name: "Stone Washed Chambray",
    price: "$17.30",
    weight: "130 GSM",
    width: '58"',
    refId: "MA-CH-SW",
    badge: null,
    badgeStyle: null,
    category: "Linen",
    season: "SS 2024",
    origin: "Bandung, Indonesia",
    composition: "100% Cotton",
    finish: "Stone Washed",
    stock: 73,
    dominantColors: ["#9e9e9e"],
    description:
      "A lightweight stone-washed chambray with the aesthetic of denim at a fraction of the weight. Perfect for shirts, dresses, and summer workwear demanding both style and breathability.",
    archivistNote:
      "Stone washing imparts a faded, lived-in aesthetic that typically takes years of wear to achieve naturally. Our process uses smooth river stones and biological enzymes rather than pumice to preserve the fabric's structural integrity.",
    features: [
      "Lightweight at 130 GSM for hot-weather comfort",
      "Consistent stone-washed fading across the bolt",
      "Excellent colorfastness to repeated washing",
    ],
    careInstructions:
      "Machine wash cold. Tumble dry low. Iron on medium. Wash separately for first 3 washes.",
    certifications: ["OEKO-TEX® Standard 100"],
    thumbnails: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhDUcd6ZQQQrdqQY7O9fkMBBtPQ7UEosuE67pN_ahKhUJnSm-CRMJg5kZEzEQ6_t4WDn2THmoJzAVj1Pt8EHBV9eveRnwWE3H9jb7zJWY8EoGVZRqmNfglJdpFSFftXDQ-uctW7MWnuLRnf9jVChsaqs_c32Dkp1rHsb-S1wagOjLw_aUTKLXDJBUTsf7I-ee4HER2Q-njBn4IvgfJcSzGCGTrhMx4GOHn5iFwfEERKHT0PxB5Y0WD_UlFKn7LWJt9FpwAvrfkOGr",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBPArA2wgo13B-2rYpu2JaNRQmGDK4X7bj2ERo4mlyyab02YYd2jUmun17LdQw0TJ8t52YY3vDbXbfNvoz74HGhHk_Q3DeTPj9ue8I9og6bqDkT6p4p-9Bp80j8jbdQMabda6XVlfnzmEB5YhV8qOH6hZ7SGmGwaaSkCgNrlFJjC2lmRuqoshv1n3-4xguWRGfFw_djD1KrML6dxTTbQkqrzG1uwe_mPK7KkhaK-xDwX7Jpm6RWFNwT1Z1KjD3T79BXTuExzfmW8grs",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCafTPK05ci3y1U4pP-Mm9vAVnc-jgQoGsi7skKtPyIZKjV36Iee3-9LzUb9J20mFtz_p31gmss6McV54qOgkmGls9DHPpC1acD9emPKHTuW_WKkDSx8xKeQ-5GjwK9ZGUKJadzCZV7CPFOyjXhPDZOnP0mYx05xsOGzjiuKmNlcmHcRqgxv95Rl7qZFiNF94qqMEa9CKKU9dWa9XmZwUSgvTFTNCB5Mwu6ldYx__1QBwWGvcVjORWWAyTFmiGTlrD5j64Y5n5gxcCj",
    ],
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCuTlDUud90HVv0VsNJtYtkF3VwfQMQtcxIXoCEogmeNr71S4Sc5w2qafg69Rz2kZNgKJCqxDW2tWZ3Qv4I7RKjp-BwhlBrsUyt9MXKuGnKadMaaCnG6PG2vd0Q4Ie7ABf89kkVzsozB1rHpd_QOz-iMgDTejjZzbLJKnr_6fma1xXhuHKc0WT8TIxHF8xOZhGjN3wvZYAJShPlATASabJmBhHFFFOhNsbxzlwic8_byejymTQcGXxtRA0XJDTsHgwqxl_QLmCJvmrH",
  },
];

export const SUBCATEGORIES = {
  All: ["All Cotton Types", "Combed", "Carded", "Pique"],
  Cotton: ["All Cotton Types", "Combed", "Carded", "Pique"],
  Linen: ["All Linen Types", "Stone Washed", "Raw", "Washed"],
  Knit: ["All Knit Types", "Jersey", "French Terry", "Fleece"],
  Specialty: ["All Specialty", "Silk", "Hemp", "Denim"],
};

export const ITEMS_PER_PAGE = 6;
